	
using System;
using System.Linq;
using System.Text;
using System.Data;
using System.Collections.Generic;

namespace BikeShop.Domain
{
    // ############################################################################
    // #
    // #        ---==>  T H I S  F I L E  W A S  G E N E R A T E D  <==---
    // #
    // # This file was generated by the CodeGen Prototype
    // # Generated on 11/22/2014 12:32:31 AM
    // #
    // # Edits to this file may cause incorrect behavior and will be lost
    // # if the code is regenerated.
    // #
    // ############################################################################
	
	// BikeShop Unit-of-Work

	public partial class BikeShopUnitOfWork : UnitOfWork
	{
		public BikeShopUnitOfWork() : base(new BikeShopDb()) { }
	}
}
